### ISSUE TITLE
Feat: Add support for asynchronous fetching of feature toggles

### ISSUE THREAD

**Issue by markunl** [Unleash/unleash-client-php#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the new feature

_Filing per discussion with @sighphyre_ 

Currently the PHP SDK does not support the asynchronous fetching of feature toggles from the upstream Edge/Proxy/unleash instance.

This means clients see increased response times while the SDK syncs with the upstream Edge/Proxy/unleash instance, where cache TTL is 30 sec and `is_enabled` method calls Unleash edge/instance after 30 sec have elapsed. This is especially relevant in scenarios where large payload responses are expected from Unleash (i.e large numbers of feature toggles and activation strategies).

Recent updates to PHP allow for asynchronous synchronization. Can support for this be implemented into the SDK? Let me know if any questions come up.

**Comment by RikudouSage** [comment]
@markunl @sighphyre 

I honestly don't think this is possible in a reasonable and universal way.

While php theoretically has support for async, it's not used asynchronously in most cases, this is the standard flow of a php app:

- you have some webserver (nginx, apache, caddy, whatever)
- that webserver either supports php directly (apache) or uses fpm (pretty much every serious webserver there is)
- when a request hits your webserver, it spawns a worker (or reuses an existing one but this is an implementation detail), the worker spawns a php process which handles the request and returns a html response, the process then exits

This all happens every request - php is usually used fully stateless.

To illustrate:

```php
final class App {
    public static bool $initialized = false;
}

var_dump(App::$initialized);
App::$initialized = true;
```

On every request it dumps `false` because every request is its own process and no state is shared.

So given the constraints (every request = spawn a php process, process the request, the process dies), it's not possible to have a meaningful async implementation. Either way you would have to wait for the async completion before sending a response (if we made this "async" the only thing that changes is that the fetching of toggles theoretically happens at the end of the request instead of the mdidle, but you still have to wait before sending the response).

There are various async frameworks (swoole, React PHP and AMP PHP from the top of my head) but you need to structure your whole application around it because there's no event loop in php (that's basically what all those frameworks do - provide an event loop and provide alternative async functions for common sync php functions). Note that minority of applications work like that.

IMO we have these options:

1. write integrations between this library and the mentioned frameworks (a lot of work, possibly duplicated logic in multiple libraries)
2. add additional `isEnabledAsync()` and basically support both sync and async (the most work and a lot of added complexity for minuscule gains)
3. expose functionality to easily fetch the repository and store it in cache for use with external systems (the easiest way and also the de-facto standard way - the lack of async in php has historically been solved by using external systems like cron and job queues)
4. do both 2. and 3.

Again, only a handful of applications support async, most are still the shared-nothing architecture I've been describing, I'm not sure options 1. and 2. are worth the time it will take to rewrite it.

Feel free to hit me on Slack if you want to chat about it a bit.

**Comment by sighphyre** [comment]
I don't believe this will solve the issues we hoped it would solve and it's also a major redesign of... well... everything. I'm going to close this and mark it as "won't do" but if someone ever has a need and a convincing argument for reconsidering it, please feel free to reopen

**Comment by xico42** [comment]
@sighphyre regarding this subject, the [split](https://www.split.io/) sdk does this exact same thing by providing the [split-synchronizer](https://help.split.io/hc/en-us/articles/360019686092) component.

It uses a redis storage between the SDK and the synchronizer. The synchronizer runs in another process and peridiocally syncs data from the server into redis. Then, the SDK fetches data from this shared redis instance.

Couldn't a similar approach be implemented? Maybe by using a custom BootstrapProvider that fetches data from redis and maintaining another process that fetches data from unleash and poulates a redis database?

**Comment by sighphyre** [comment]
Hey @xico42, that's a pretty neat idea. We actually went in a very different way with this because the thing that was driving this issue wasn't actually the async nature of this but deserialising large data responses from Redis.

We support Proxy mode for this SDK, which is intended to be used against an Edge instance running nearby. It's still synchronous but the short hop combined with low data overhead has been good enough so far

**Comment by xico42** [comment]
So the deserialization of a large object from redis might be worse (or very similar) than an extra call for a nearby edge instance, right?

I am going to try out this strategy that I have commented and do some sort of benchmark to see how it goes.

Here at the company I work for we are in a process of migrating from split to a self hosted unleash instance. I am afraid that this extra network call might have a bad impact in our system, at least in comparison with the approach taken by the split SDK.

When I have a clearer understanding about the impact of it I will bring here the conclusion I've come to.

Depending on the results, I might propose something regarding the topic.

**Comment by RikudouSage** [comment]
@xico42 I think it could be achieved pretty easily here, put large enough ttl in the php sdk in the target application and then whip up a separate application (the synchronizer) that will simply get the features at a lower interval, that way the cache is never stale and is always populated from a different process. Or you can even entirely disable network access for the SDK (but then you lose the metrics on flags use).

Edit: Well, even the metrics could be made to work without network access, the synchronizer would have to take care of reporting them and a custom implementation of `\Unleash\Client\Metrics\MetricsSender` might be needed (it could be made to work with the existing one, but it would rely too much on internal behavior which can change).

**Comment by xico42** [comment]
@RikudouSage I believe there might be a problem with this solution. If the target application provides a large TTL, the synchronizer (if implemented by using the SDK itself) won't be able to update the cache because it will still be valid by the time the it runs.

Unless, the stale cache configured at the "synchronizer" SDK points to the main cache configured in the target application.

Is this how you imagined the implementation?

**Comment by michael-schmetter** [comment]
@xico42 @RikudouSage 
Could this be as simple as this?
https://github.com/Unleash/unleash-client-php/pull/211

**Comment by RikudouSage** [comment]
Well, it's a building block for what @xico42 wanted, but I wouldn't say it's the full implementation of what was discussed.

**Comment by michael-schmetter** [comment]
My approach would keep the problematic of running the process and orchestration the cache refresh out of the SDK, so that the user needs to take care of that. We would only offer the possibility to refresh the TTL of the cache entries without reaching the original TTL.

What do you think is missing?
