### ISSUE TITLE
feat: Use HTTP statuses to backoff when needed

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash-client-php#192]
### Describe the feature request

In order to reduce load on servers, as well as save our users some bandwidth, I'd like for this SDK to react to http status codes, and not just keep requesting at the same frequency if the server is telling it to chill out.

### Background

Part of a cross-SDK initiative to make all our SDKs respect http statuses in order to save ourselves and our users for bandwidth/cpu usage that adds no value to either the server or the client.

### Solution suggestions

https://github.com/Unleash/unleash-client-node/pull/537 follows the correct pattern. Use 404, 429 or 50x statuses to reduce polling frequency. On 401 or 403 log and don't keep polling - your user probably needs to update their key before there's any point in continuing to hit the server.

**Comment by RikudouSage** [comment]
This might be a little harder than in other SDKs because PHP (the way it's commonly used in web environments) doesn't use any shared state, meaning no variables persist across requests and thus detecting when the app has been redeployed (and the changes to the frequency should be reset to configured values) is hard.
