### ISSUE TITLE
Bug: PHP version dependency was bumped from 8.2 -> 8.3 in a patch release, was this intentional?

### ISSUE THREAD

**Issue by jamisonbryant** [Unleash/unleash-client-php#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `composer.json` dependencies for this library now list php8.3 as the minimum version to use `unleash/client`. What's odd is this change was made in v2.5.283. The next patch version back, v2.5.282, is still PHP8.2.

We were just wondering if this was intentional? It's a pretty big change to make in a patch version update.

### To reproduce

1. Install PHP8.2
2. Update your `composer.json` to point at release 2.5.283 of this package.
3. Run `composer install` - note PHP dependency version check failure
4. Update your `composer.json` to point at 2.5.282 or any other version older than that in the v2 range
5. Run `composer install` - note installation is successful

### Sample code (optional)

```php
Your Composer dependencies require a PHP version ">= 8.3.0".
```

### Version

2.5.283

### Expected behavior

Maintain PHP8.2 as the minimum version for all patch version upgrades. A minor or major version upgrade would be more appropriate for a shift of this size.

**Comment by RikudouSage** [comment]
The way this project works is that the code itself is written in the newest php version and then automatically transpiled to older versions. Meaning nothing really changes for you, you can use v2.5.282, which contains all the code from v2.5.283, but with code that doesn't work on PHP 8.2 changed to be compatible. 

This goes all the way down to PHP 7.2, meaning even 7.2 is supported with the same version, it just has 72 as a suffix, v2.5.272.

The way this works is that composer installs the latest supported version. Because 2.5.283 is larger than 2.5.282, composer prefers it in require/update, but if your php version doesn't match, it tries the next latest (2.5.282), then the next (2.5.281) and so on.
